### PR TITLE
Make property values observable

### LINKED ISSUE #9: There is no way of getting notified when a property value is changes via the API
Example: When i have a light exposed via the wot api and a request comes in changing the on/off state of that light. The value inside the property is changed, but there is no way to forward that change to the actual light, without polling the property.getValue() method all the time.

Suggestion: Make the properties have a Value object that contains a Java8 `Consumer` that knows how to set the actual on/off state of the light (flip a GPIO pin etc.)

### PR DESCRIPTION
**Pull request by Timmeey**
This adds a value object to the properties, which contains the actual value, and a method to forward any changes to the actual thing (light etc.) closes #9 

Also updates the README.md with more detailed examples

### CODE REVIEW

**Comment by mrstegeman** [comment]
@Timmeey I like the idea here. Would you mind creating a second example server, though, instead of modifying the original? I use the original for compatibility testing right now.

**Comment by Timmeey** [comment]
@mrstegeman I restored the previous TestServer. But having the value in the Properties as flat datatypes in incompatible to my changes. Check and see if you can live with those small changes. This does not affect the REST api or the API behaviour.

**Review by Timmeey — COMMENTED** [review]
Wow, thanks for the effort. Very much appreciated.

**Comment by mrstegeman** [comment]
@Timmeey I'm in the process of translating this to Python and Javascript as well. Once that is done, I'll push up a final set of changes and then get them merged.

I try to keep all the libraries in line with each other. Likewise, I keep a test server in each that produces the Thing Description found at the top of our spec. It makes testing really easy. That's why I wanted you to keep the original server 😄

**Pull request merged**
